apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filebrowser.fullname" . }}-auth
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
data:
  ADMIN_USERNAME: {{ .Values.auth.adminUsername | b64enc | quote }}
{{- if .Values.auth.adminPassword }}
  ADMIN_PASSWORD: {{ .Values.auth.adminPassword | b64enc | quote }}
{{- else }}
  ADMIN_PASSWORD: {{ randAlphaNum 50 | b64enc | quote }}
{{- end }}
